import { useEffect, useState } from 'react'
import styles from './App.module.css'
import { api, type Order, type OrderItem, type Product, type Table, type TableDetail, type User } from './api'

type Role = 'ADMINISTRADOR' | 'MOZO' | 'COCINERO'
type Cart = Record<number, number>

const money = (value: number) => `S/ ${Number(value).toFixed(2)}`
const roleLabel: Record<Role, string> = { ADMINISTRADOR: 'Administrador', MOZO: 'Mozo', COCINERO: 'Cocinero' }

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setLoading(true); setError('')
    try { onLogin(await api.login(username, password)) } catch { setError('Usuario o contraseña incorrectos') } finally { setLoading(false) }
  }
  return <main className={styles.loginShell}>
    <section className={styles.loginStory}><div className={styles.storyContent}><div className={styles.loginBrand}><span className={styles.brandMark}>VM</span><strong>El Viejo Madero</strong></div><div className={styles.storyCopy}><h1>Cocina de leña,<br />servicio de siempre.</h1><p>Pedidos en salón, coordinación de cocina y gestión de la carta en un solo lugar.</p></div><span className={styles.storyCaption}>Sistema de gestión interno</span></div></section>
    <section className={styles.loginPanel}><div className={styles.loginFormWrap}><div className={styles.referenceBrand}><span className={styles.referenceLogo}>VM</span><strong>El Viejo Madero</strong></div><h2>Iniciar sesión</h2><p className={styles.loginIntro}>Ingresa con tu usuario para continuar.</p><form className={styles.loginForm} onSubmit={submit}><label htmlFor="username">Usuario</label><input id="username" type="text" value={username} onChange={event => setUsername(event.target.value)} required /><label htmlFor="password">Contraseña</label><input id="password" type="password" value={password} onChange={event => setPassword(event.target.value)} required />{error && <p className={styles.loginError}>{error}</p>}<button className={styles.loginButton} disabled={loading}>{loading ? 'Validando...' : 'Entrar'}</button></form><p className={styles.demoAccess}>Usuarios iniciales: <b>admin</b>, <b>mozo</b> y <b>cocina</b>.</p></div></section>
  </main>
}

function Header({ user, onLogout }: { user: User; onLogout: () => void }) {
  return <header className={styles.waiterHeader}><div className={styles.waiterBrand}><span className={styles.waiterLogo}>VM</span><div><strong>El Viejo Madero</strong><small>{roleLabel[user.role as Role]} · {user.full_name}</small></div></div><button className={styles.logoutButton} onClick={onLogout}>Salir</button></header>
}

function Waiter({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [tables, setTables] = useState<Table[]>([]); const [products, setProducts] = useState<Product[]>([]); const [readyOrders, setReadyOrders] = useState<Order[]>([]); const [readyItems, setReadyItems] = useState<Record<number, OrderItem[]>>({}); const [selected, setSelected] = useState<Table | null>(null); const [busyTable, setBusyTable] = useState<TableDetail | null>(null); const [editingOrderId, setEditingOrderId] = useState<number | null>(null); const [cart, setCart] = useState<Cart>({}); const [customerName, setCustomerName] = useState(''); const [message, setMessage] = useState('')
  const loadReadyOrders = async () => { const orders = await api.orders('READY'); const details = await Promise.all(orders.map(order => api.orderDetail(order.id))); setReadyOrders(orders); setReadyItems(Object.fromEntries(details.map(detail => [detail.id, detail.items]))) }
  useEffect(() => { Promise.all([api.tables(), api.products(), loadReadyOrders()]).then(([loadedTables, loadedProducts]) => { setTables(loadedTables as Table[]); setProducts(loadedProducts as Product[]) }).catch(error => setMessage(error.message)); const refresh = () => { void loadReadyOrders().catch(error => setMessage(error.message)) }; const interval = window.setInterval(refresh, 3000); window.addEventListener('focus', refresh); return () => { window.clearInterval(interval); window.removeEventListener('focus', refresh) } }, [])
  const add = (id: number) => setCart(current => ({ ...current, [id]: (current[id] ?? 0) + 1 }))
  const decrease = (id: number) => setCart(current => { const next = { ...current }; if ((next[id] ?? 0) <= 1) delete next[id]; else next[id] -= 1; return next })
  const remove = (id: number) => setCart(current => { const next = { ...current }; delete next[id]; return next })
  const cartProducts = products.filter(product => cart[product.id]); const total = cartProducts.reduce((sum, product) => sum + Number(product.base_price) * cart[product.id], 0)
  const save = async () => { if (!selected || !cartProducts.length || !customerName.trim()) return; const items = cartProducts.map(product => ({ productId: product.id, productName: product.name, price: Number(product.base_price), quantity: cart[product.id], notes: '' })); if (editingOrderId) await api.updateOrderItems(editingOrderId, customerName.trim(), items); else await api.createOrder(selected.id, user.id, customerName.trim(), items); setMessage(editingOrderId ? 'Pedido actualizado' : 'Pedido registrado y listo para confirmar'); setCart({}); setCustomerName(''); setEditingOrderId(null); setSelected(null); setTables(await api.tables()) }
    const editBusyOrder = () => { if (!busyTable) return; setSelected(busyTable.table); setBusyTable(null); setEditingOrderId(busyTable.order.id); setCustomerName(busyTable.order.customer_name ?? ''); setCart(Object.fromEntries(busyTable.order.items.map(item => [item.product_id, item.quantity]))) }
    const releaseBusyTable = async () => { if (!busyTable || !window.confirm('¿Los clientes se retiraron? La mesa quedará libre y sus pedidos se cerrarán.')) return; await api.deleteOrder(busyTable.order.id); setBusyTable(null); setTables(await api.tables()); setMessage(`Mesa ${busyTable.table.code} liberada`) }
  const selectTable = async (table: Table) => { if (table.status === 'FREE') { setSelected(table); return } try { setBusyTable(await api.tableDetail(table.id)) } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo cargar el detalle de la mesa') } }
  const closeBusyTable = () => setBusyTable(null)
  const serve = async (order: Order) => { await api.updateOrder(order.id, 'SERVED', user.id); await Promise.all([loadReadyOrders(), api.tables().then(setTables)]) }
  const renderReadyOrders = () => <section className={styles.readySection}><div className={styles.readyHeading}><div className={styles.waiterSectionTitle}><span className={styles.readyIcon}>♧</span><h2>Listos para entregar</h2><span className={styles.countBadge}>{readyOrders.length}</span></div><button className={styles.refreshReady} onClick={() => void loadReadyOrders()} aria-label="Actualizar pedidos listos">Actualizar</button></div>{readyOrders.length === 0 ? <p className={styles.emptyReady}>No hay pedidos listos para entregar.</p> : <div className={styles.readyOrders}>{readyOrders.map(order => <article className={styles.readyOrderCard} key={order.id}><div className={styles.readyOrderHeader}><strong>{order.code}</strong><span>Mesa {order.table_code}</span></div>{order.customer_name && <small>{order.customer_name}</small>}<div className={styles.readyOrderItems}>{(readyItems[order.id] ?? []).map(item => <div key={item.product_id}><b>{item.quantity}x</b><span>{item.product_name}</span></div>)}</div><button onClick={() => void serve(order)}>Servir a la mesa</button></article>)}</div>}</section>
  if (busyTable) return <><Header user={user} onLogout={onLogout} /><main className={styles.waiterContent}><section className={styles.waiterIntro}><h1>Mesas del salón</h1><p>Selecciona una mesa para registrar un pedido.</p></section><div className={styles.waiterTableGrid}>{tables.map(table => <button className={styles.waiterTableCard} key={table.id} onClick={() => void selectTable(table)}><span className={styles.chairIcon}>▱</span><strong>{table.code}</strong><span className={styles.waiterStatus}>{table.status === 'FREE' ? 'Libre' : 'Ocupada'}</span>{table.customer_name && <small className={styles.tableCustomer}>{table.customer_name}</small>}</button>)}</div><div className={styles.modalBackdrop} onClick={closeBusyTable}><section className={styles.tableModal} onClick={event => event.stopPropagation()}><header><h2>Mesa {busyTable.table.code}</h2><button className={styles.modalClose} onClick={closeBusyTable} aria-label="Cerrar">x</button><p>Detalle de lo que está consumiendo la mesa.</p></header><div className={styles.modalTotal}><span>Consumo total</span><strong>{money(Number(busyTable.order.total))}</strong></div><article className={styles.modalOrder}><div className={styles.modalOrderHeader}><strong>{busyTable.order.code}</strong><span>{busyTable.order.status === 'SERVED' ? 'Servido' : busyTable.order.status}</span></div>{busyTable.order.customer_name && <small>Cliente: {busyTable.order.customer_name}</small>}{busyTable.order.items.map(item => <div className={styles.modalItem} key={item.product_id}><strong>{item.quantity}x</strong><span>{item.product_name}</span><span>{money(Number(item.line_total))}</span></div>)}<div className={styles.modalSubtotal}><span>Subtotal</span><strong>{money(Number(busyTable.order.total))}</strong></div></article><div className={styles.modalActions}><button onClick={editBusyOrder}>+ &nbsp;Agregar pedido a esta mesa</button><button className={styles.releaseButton} onClick={() => void releaseBusyTable()}>Liberar mesa</button></div></section></div></main></>
  if (selected) return <><Header user={user} onLogout={onLogout} /><main className={styles.orderContent}><button className={styles.backButton} onClick={() => setSelected(null)}>← Volver a mesas</button><div className={styles.orderTitle}><h1>Mesa {selected.code}</h1><span>{selected.status === 'FREE' ? 'Disponible' : 'Ocupada'}</span></div><label className={styles.customerField}>Nombre del cliente<input value={customerName} onChange={event => setCustomerName(event.target.value)} placeholder="Ej. Ana García" maxLength={120} required /></label><div className={styles.orderLayout}><div className={styles.menuList}>{products.map(product => <button className={styles.menuItem} key={product.id} onClick={() => add(product.id)}><span><strong>{product.name}</strong><small>{product.description}</small></span><b>{money(Number(product.base_price))}</b><em>+</em></button>)}</div><aside className={styles.cartPanel}><h2>Pedido</h2>{cartProducts.map(product => <div className={styles.cartItem} key={product.id}><span>{cart[product.id]}x</span><strong>{product.name}</strong><div className={styles.cartActions}><button type="button" onClick={() => decrease(product.id)} aria-label={`Disminuir ${product.name}`}>-</button><button type="button" onClick={() => add(product.id)} aria-label={`Aumentar ${product.name}`}>+</button><button type="button" onClick={() => remove(product.id)} aria-label={`Eliminar ${product.name}`}>x</button></div><b>{money(Number(product.base_price) * cart[product.id])}</b></div>)}{!cartProducts.length && <p className={styles.emptyCart}>Agrega platos desde la carta.</p>}<div className={styles.cartTotal}><span>Total</span><strong>{money(total)}</strong></div><button className={styles.loginButton} disabled={!cartProducts.length || !customerName.trim()} onClick={save}>{editingOrderId ? 'Actualizar pedido' : 'Registrar pedido'}</button></aside></div></main></>
  return <><Header user={user} onLogout={onLogout} /><main className={styles.waiterContent}>{renderReadyOrders()}<section className={styles.tablesSection}><div className={styles.tablesHeading}><div className={styles.waiterSectionTitle}><span className={styles.tablesIcon}>▣</span><h2>Mesas del salón</h2></div></div><p>Selecciona una mesa para registrar un pedido.</p>{message && <p>{message}</p>}<div className={styles.waiterTableGrid}>{tables.map(table => <button className={styles.waiterTableCard} key={table.id} onClick={() => void selectTable(table)}><span className={styles.chairIcon}>▱</span><strong>{table.code}</strong><span className={styles.waiterStatus}>{table.status === 'FREE' ? 'Libre' : 'Ocupada'}</span>{table.customer_name && <small className={styles.tableCustomer}>{table.customer_name}</small>}</button>)}</div></section></main></>
}

function Kitchen({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [orders, setOrders] = useState<Order[]>([]); const [itemsByOrder, setItemsByOrder] = useState<Record<number, OrderItem[]>>({}); const [error, setError] = useState('')
  const load = async () => { try { const loadedOrders = await api.orders(); const details = await Promise.all(loadedOrders.map(order => api.orderDetail(order.id))); setOrders(loadedOrders); setItemsByOrder(Object.fromEntries(details.map(detail => [detail.id, detail.items]))) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'No se pudieron cargar las comandas') } }
  useEffect(() => { void load() }, [])
  const move = async (order: Order, status: string) => { await api.updateOrder(order.id, status, user.id); await load() }
  const columns = [['OPEN,CONFIRMED', 'Nuevos', 'IN_KITCHEN'], ['IN_KITCHEN', 'En preparación', 'READY'], ['READY', 'Listos para entregar', 'READY']]
  return <><Header user={user} onLogout={onLogout} /><main className={styles.kitchenContent}><section className={styles.kitchenIntro}><h1>Cocina — comandas</h1><p>Actualiza el estado a medida que avanza cada pedido.</p>{error && <p>{error}</p>}</section><section className={styles.kitchenBoard}>{columns.map(([status, title, next]) => <article className={styles.kitchenColumn} key={status}><div className={styles.kitchenColumnHeading}><h2>{title}</h2><span className={styles.kitchenCount}>{orders.filter(order => status.split(',').includes(order.status)).length}</span></div>{orders.filter(order => status.split(',').includes(order.status)).map(order => <div className={styles.kitchenCard} key={order.id}><div className={styles.kitchenCardHeader}><strong>{order.code}</strong><small>Mesa {order.table_code}</small></div>{order.customer_name && <span>Cliente: {order.customer_name}</span>}<div className={styles.kitchenItems}>{(itemsByOrder[order.id] ?? []).map(item => <div className={styles.kitchenItem} key={item.product_id}><strong>{item.quantity}x</strong><span>{item.product_name}</span></div>)}</div><span className={styles.kitchenTotal}>{money(Number(order.total))}</span>{status !== 'READY' ? <button onClick={() => void move(order, next)}>{next === 'IN_KITCHEN' ? 'Tomar pedido' : 'Marcar listo'}</button> : <span className={styles.readyKitchenLabel}>Esperando al mesero</span>}</div>)}</article>)}</section></main></>
}

function Admin({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [users, setUsers] = useState<Array<User & { active: boolean }>>([])
  const [orders, setOrders] = useState<Order[]>([])
  const [products, setProducts] = useState<Product[]>([])
  const [categories, setCategories] = useState<Array<{ id: number; name: string }>>([])
  const [tab, setTab] = useState<'Resumen' | 'Carta' | 'Empleados'>('Resumen')
  const [error, setError] = useState('')
  const [showProductForm, setShowProductForm] = useState(false)
  const [editingProduct, setEditingProduct] = useState<Product | null>(null)
  const [showUserForm, setShowUserForm] = useState(false)
  const [editingUser, setEditingUser] = useState<(User & { active: boolean }) | null>(null)
  const [productForm, setProductForm] = useState({ category: '', name: '', description: '', price: '', prepMinutes: '10' })
  const [userForm, setUserForm] = useState({ fullName: '', username: '', password: '', role: 'MOZO' })
  const load = async () => {
    try {
      const [loadedUsers, loadedOrders, loadedProducts, loadedCategories] = await Promise.all([api.users(), api.orders(), api.adminProducts(), api.categories()])
      setUsers(loadedUsers); setOrders(loadedOrders); setProducts(loadedProducts); setCategories(loadedCategories)
      if (!productForm.category && loadedCategories[0]) setProductForm(current => ({ ...current, category: loadedCategories[0].name }))
    } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'No se pudo cargar la administración') }
  }
  useEffect(() => {
    const loadInitialData = async () => {
      try {
        const [loadedUsers, loadedOrders, loadedProducts, loadedCategories] = await Promise.all([api.users(), api.orders(), api.adminProducts(), api.categories()])
        setUsers(loadedUsers); setOrders(loadedOrders); setProducts(loadedProducts); setCategories(loadedCategories)
        if (loadedCategories[0]) setProductForm(current => ({ ...current, category: loadedCategories[0].name }))
      } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'No se pudo cargar la administración') }
    }
    void loadInitialData()
  }, [])
  const createUser = async (event: React.FormEvent) => { event.preventDefault(); if (editingUser) await api.updateUser(editingUser.id, userForm); else await api.createUser(userForm); setEditingUser(null); setUserForm({ fullName: '', username: '', password: '', role: 'MOZO' }); setShowUserForm(false); await load() }
  const createProduct = async (event: React.FormEvent) => { event.preventDefault(); const data = { ...productForm, price: Number(productForm.price), prepMinutes: Number(productForm.prepMinutes) }; if (editingProduct) await api.updateProduct({ ...editingProduct, name: data.name, description: data.description, category: data.category, base_price: data.price }, editingProduct.available !== false); else await api.createProduct(data); setEditingProduct(null); setProductForm(current => ({ ...current, name: '', description: '', price: '' })); setShowProductForm(false); await load() }
  return <><Header user={user} onLogout={onLogout} /><main className={styles.adminContent}>
    <div className={styles.adminIntro}><div><h1>Administración</h1><p>Usuarios, roles, carta y operación del restaurante.</p></div><nav className={styles.adminTabs}>{(['Resumen', 'Carta', 'Empleados'] as const).map(item => <button key={item} className={tab === item ? styles.adminTabActive : ''} onClick={() => setTab(item)}>{item}</button>)}</nav></div>
    {error && <p className={styles.loginError}>{error}</p>}
    {tab === 'Resumen' && <section className={styles.adminStats}><div className={styles.adminStat}><div><small>Pedidos activos</small><strong>{orders.filter(order => !['SERVED', 'CANCELLED'].includes(order.status)).length}</strong></div></div><div className={styles.adminStat}><div><small>Usuarios activos</small><strong>{users.filter(item => item.active).length}</strong></div></div><div className={styles.adminStat}><div><small>Ventas registradas</small><strong>{money(orders.reduce((sum, order) => sum + Number(order.total), 0))}</strong></div></div></section>}
    {tab === 'Carta' && <section className={styles.adminOrders}><div className={styles.adminSectionHeader}><h2>Platos y disponibilidad</h2><button className={styles.adminActionButton} onClick={() => { setEditingProduct(null); setShowProductForm(current => !current) }}>{showProductForm ? 'Cancelar' : 'Nuevo plato'}</button></div>{showProductForm && <form className={styles.adminForm} onSubmit={createProduct}><input placeholder="Nombre del plato" value={productForm.name} onChange={event => setProductForm({ ...productForm, name: event.target.value })} required /><input placeholder="Descripción" value={productForm.description} onChange={event => setProductForm({ ...productForm, description: event.target.value })} /><select value={productForm.category} onChange={event => setProductForm({ ...productForm, category: event.target.value })} required>{categories.map(category => <option key={category.id}>{category.name}</option>)}</select><input type="number" min="0" step="0.01" placeholder="Precio" value={productForm.price} onChange={event => setProductForm({ ...productForm, price: event.target.value })} required /><input type="number" min="1" placeholder="Minutos de preparación" value={productForm.prepMinutes} onChange={event => setProductForm({ ...productForm, prepMinutes: event.target.value })} required /><button className={styles.adminActionButton}>{editingProduct ? 'Guardar cambios' : 'Guardar plato'}</button></form>}<div className={styles.adminTableWrap}><table className={styles.adminTable}><thead><tr><th>Plato</th><th>Categoría</th><th>Precio</th><th>Estado</th><th></th></tr></thead><tbody>{products.map(product => <tr key={product.id}><th>{product.name}</th><td>{product.category}</td><td>{money(Number(product.base_price))}</td><td>{product.available === false ? 'No disponible' : 'Disponible'}</td><td><button onClick={() => { setEditingProduct(product); setProductForm({ category: product.category, name: product.name, description: product.description ?? '', price: String(product.base_price), prepMinutes: '10' }); setShowProductForm(true) }}>Editar</button> <button onClick={async () => { await api.updateProduct(product, product.available === false); await load() }}>{product.available === false ? 'Activar' : 'Desactivar'}</button></td></tr>)}</tbody></table></div></section>}
    {tab === 'Empleados' && <section className={styles.adminOrders}><div className={styles.adminSectionHeader}><h2>Empleados y roles</h2><button className={styles.adminActionButton} onClick={() => { setEditingUser(null); setUserForm({ fullName: '', username: '', password: '', role: 'MOZO' }); setShowUserForm(current => !current) }}>{showUserForm ? 'Cancelar' : 'Nuevo empleado'}</button></div>{showUserForm && <form className={styles.adminForm} onSubmit={createUser}><input placeholder="Nombre completo" value={userForm.fullName} onChange={event => setUserForm({ ...userForm, fullName: event.target.value })} required /><input placeholder="Usuario" value={userForm.username} onChange={event => setUserForm({ ...userForm, username: event.target.value })} required /><input type="password" placeholder={editingUser ? 'Nueva contraseña (opcional)' : 'Contraseña'} value={userForm.password} onChange={event => setUserForm({ ...userForm, password: event.target.value })} required={!editingUser} /><select value={userForm.role} onChange={event => setUserForm({ ...userForm, role: event.target.value })}><option value="MOZO">Mozo</option><option value="COCINERO">Cocinero</option><option value="ADMINISTRADOR">Administrador</option></select><button className={styles.adminActionButton}>{editingUser ? 'Guardar cambios' : 'Guardar empleado'}</button></form>}<div className={styles.adminTableWrap}><table className={styles.adminTable}><thead><tr><th>Nombre</th><th>Usuario</th><th>Rol</th><th>Estado</th><th></th></tr></thead><tbody>{users.map(item => <tr key={item.id}><th>{item.full_name}</th><td>{item.username}</td><td>{roleLabel[item.role as Role] ?? item.role}</td><td>{item.active ? 'Activo' : 'Inactivo'}</td><td><button onClick={() => { setEditingUser(item); setUserForm({ fullName: item.full_name, username: item.username, password: '', role: item.role }); setShowUserForm(true) }}>Editar</button> <button onClick={async () => { await api.toggleUser(item.id, !item.active); await load() }}>{item.active ? 'Desactivar' : 'Activar'}</button></td></tr>)}</tbody></table></div></section>}
  </main></>
}

function App() {
  const [user, setUser] = useState<User | null>(() => { const stored = localStorage.getItem('restaurant-user'); return stored ? JSON.parse(stored) : null })
  const logout = () => { localStorage.removeItem('restaurant-user'); setUser(null) }
  const login = (nextUser: User) => { localStorage.setItem('restaurant-user', JSON.stringify(nextUser)); setUser(nextUser) }
  if (!user) return <Login onLogin={login} />
  if (user.role === 'MOZO') return <Waiter user={user} onLogout={logout} />
  if (user.role === 'COCINERO') return <Kitchen user={user} onLogout={logout} />
  return <Admin user={user} onLogout={logout} />
}

export default App
